# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(221E21)
$foreground = rgb(F1D6F1)
$color0 = rgb(484548)
$color1 = rgb(682032)
$color2 = rgb(694369)
$color3 = rgb(73466A)
$color4 = rgb(A85866)
$color5 = rgb(9A639A)
$color6 = rgb(A268A2)
$color7 = rgb(E3BDE3)
$color8 = rgb(9F849F)
$color9 = rgb(8B2B43)
$color10 = rgb(8C5A8B)
$color11 = rgb(9A5D8D)
$color12 = rgb(E07688)
$color13 = rgb(CD84CD)
$color14 = rgb(D88BD8)
$color15 = rgb(E3BDE3)
