#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width          2
bspc config window_gap            12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config pointer_modifier      mod4
bspc config pointer_action1       move
bspc config pointer_action2       resize_side

# autostart
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
dunst &
bash ~/.config/polybar/launch.sh --docky
feh --bg-scale ~/wallpapers/blur1.jpg
pulseaudio --start
libinput-gestures-setup start &
xinput set-prop "ASUF1204:00 2808:0104 Touchpad" "Synaptics Scrolling Distance" -94, -94
